services:
  - docker

before_install:
  - docker run -it travisci/ubuntu-ruby:18.04 /bin/bash

stages:
  - name: Linting test
    if: type IN (push)

jobs:
  include:
    - stage: "Linting test"
      name: "Running lint testing"
      install:
        - npm install eslint --save-dev
        - ./node_modules/.bin/eslint src/main/content/_assets/js/*.js
      script:
        - ./scripts/build_gem_dependencies.sh

travis_after_all: exit