language: ruby
rvm:
  - 2.6.3

install:
  - bundle install
  - npm install eslint --save-dev
  - ./node_modules/.bin/eslint src/main/content/_assets/js/*.js

script:
  - ./scripts/build_jekyll_maven.sh 
  - echo "$GITHUB_OAUTH_TOKEN"
  
sudo: false

jobs:
  include:
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true