sudo: false

jobs:
  include:
    - stage: GitHub Release
      script: 
      - echo "$GITHUB_OAUTH_TOKEN"
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
  
